config/routes.rb
Rails.application.routes.draw do
  resources :ordered_products
  resources :orders
  resources :import_orders, controller: "import_orders"
  resources :export_orders, controller: "export_orders"
  resources :agencies
  resources :products
  resources :users
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/stat",  to: "static_pages#stat"
  get "/about", to: "static_pages#about"
  get "/help",  to: "static_pages#help"
  get "/profile", to: "users#profile"
  post "/csv/create", to: "csv#create"
  get "search/universalSearch", to: "searchs#universalSearch"
  get "search/products", to: "searchs#productSearch"
  get "search/agencies", to: "searchs#agencySearch"
  
  get "test_notify/:id", to: "tests#ping"

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"  # http://localhost:3000/sidekiq
  root "static_pages#home"
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/controllers/ordered_products_controller.rb
class OrderedProductsController < ApplicationController
  before_action :set_ordered_product, only: %i[ show edit update destroy ]

  # GET /ordered_products or /ordered_products.json
  def index
    @ordered_products = OrderedProduct.all
  end

  # GET /ordered_products/1 or /ordered_products/1.json
  def show
  end

  # GET /ordered_products/new
  def new
    @ordered_product = OrderedProduct.new
  end

  # GET /ordered_products/1/edit
  def edit
  end

  # POST /ordered_products or /ordered_products.json
  def create
    @ordered_product = OrderedProduct.new(ordered_product_params)

    respond_to do |format|
      if @ordered_product.save
        format.html { redirect_to @ordered_product, notice: "Ordered product was successfully created." }
        format.json { render :show, status: :created, location: @ordered_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ordered_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordered_products/1 or /ordered_products/1.json
  def update
    respond_to do |format|
      if @ordered_product.update(ordered_product_params)
        format.html { redirect_to @ordered_product, notice: "Ordered product was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @ordered_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ordered_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordered_products/1 or /ordered_products/1.json
  def destroy
    @ordered_product.destroy!

    respond_to do |format|
      format.html { redirect_to ordered_products_path, notice: "Ordered product was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordered_product
      @ordered_product = OrderedProduct.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def ordered_product_params
      params.expect(ordered_product: [ :quantity, :price_per_unit, :product_id, :order_id ])
    end
end

app/helpers/ordered_products_helper.rb
module OrderedProductsHelper
end

app/views/ordered_products/_form.html.erb
<%= form_with(model: ordered_product, class: "contents") do |form| %>
  <% if ordered_product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(ordered_product.errors.count, "error") %> prohibited this ordered_product from being saved:</h2>

      <ul class="list-disc ml-6">
        <% ordered_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ordered_product.errors[:quantity].none?, "border-red-400 focus:outline-red-600": ordered_product.errors[:quantity].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :price_per_unit %>
    <%= form.text_field :price_per_unit, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ordered_product.errors[:price_per_unit].none?, "border-red-400 focus:outline-red-600": ordered_product.errors[:price_per_unit].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ordered_product.errors[:product_id].none?, "border-red-400 focus:outline-red-600": ordered_product.errors[:product_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :order_id %>
    <%= form.text_field :order_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ordered_product.errors[:order_id].none?, "border-red-400 focus:outline-red-600": ordered_product.errors[:order_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/ordered_products/_ordered_product.html.erb
<div id="<%= dom_id ordered_product %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= ordered_product.quantity %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Price per unit:</strong>
    <%= ordered_product.price_per_unit %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Product:</strong>
    <%= ordered_product.product_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Order:</strong>
    <%= ordered_product.order_id %>
  </div>
</div>

app/views/ordered_products/edit.html.erb
<% content_for :title, "Editing ordered product" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ordered product</h1>

  <%= render "form", ordered_product: @ordered_product %>

  <%= link_to "Show this ordered product", @ordered_product, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to ordered products", ordered_products_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/ordered_products/index.html.erb
<% content_for :title, "Ordered products" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ordered products</h1>
    <%= link_to "New ordered product", new_ordered_product_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="ordered_products" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @ordered_products.any? %>
      <% @ordered_products.each do |ordered_product| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render ordered_product %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", ordered_product, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_ordered_product_path(ordered_product), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", ordered_product, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No ordered products found.</p>
    <% end %>
  </div>
</div>

app/views/ordered_products/new.html.erb
<% content_for :title, "New ordered product" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ordered product</h1>

  <%= render "form", ordered_product: @ordered_product %>

  <%= link_to "Back to ordered products", ordered_products_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/ordered_products/show.html.erb
<% content_for :title, "Showing ordered product" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing ordered product</h1>

  <%= render @ordered_product %>

  <%= link_to "Edit this ordered product", edit_ordered_product_path(@ordered_product), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to ordered products", ordered_products_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this ordered product", @ordered_product, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>